export const LOGIN_FETCH = 'LOGIN_FETCH';
export const LOGIN_DATA = 'LOGIN_DATA';
export const LOGOUT_FETCH = 'LOGOUT_FETCH';
export const LOGOUT_DATA = 'LOGOUT_DATA';

export const GET_USERS_FETCH = 'GET_USERS_FETCH';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_DATA_BY_FILTER_FETCH = 'GET_DATA_BY_FILTER_FETCH';
export const GET_USERS_BY_LABELS_FETCH = 'GET_USERS_BY_LABELS_FETCH';

export const GET_USERS_PENDING_DOCUMENTS_FETCH = 'GET_USERS_PENDING_DOCUMENTS_FETCH';
export const GET_USERS_PENDING_DOCUMENTS_DATA = 'GET_USERS_PENDING_DOCUMENTS_DATA';
export const FILTER_USERS_VERIFIED_DOCUMENTS = 'FILTER_USERS_VERIFIED_DOCUMENTS';

export const GET_CURRENT_USER_FETCH = 'GET_CURRENT_USER_FETCH';
export const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA';
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR';
export const CURRENT_USER_RESET = 'CURRENT_USER_RESET';

export const GET_USER_DATA_FETCH = 'GET_USER_DATA_FETCH';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';

export const DELETE_USER_LABEL_FETCH = 'DELETE_USER_LABEL_FETCH';
export const ADD_USER_LABEL_FETCH = 'ADD_USER_LABEL_FETCH';
export const EDIT_USER_LABEL_FETCH = 'EDIT_USER_LABEL_FETCH';

export const CHANGE_USER_STATE_FETCH = 'CHANGE_USER_STATE_FETCH';
export const CHANGE_USER_ROLE_FETCH = 'CHANGE_USER_ROLE_FETCH';
export const CHANGE_USER_OTP_FETCH = 'CHANGE_USER_OTP_FETCH';

export const SIGN_IN_REQUIRE_2FA = 'SIGN_IN_REQUIRE_2FA';

export const ALERT_DELETE = 'ALERT_DELETE';
export const ALERT_DATA = 'ALERT_DATA';
export const ALERT_PUSH = 'ALERT_PUSH';
export const ALERT_DELETE_BY_INDEX = 'ALERT_DELETE_BY_INDEX';

export const USER_ACTIVITY_FETCH = 'USER_ACTIVITY_FETCH';
export const USER_ACTIVITY_DATA = 'USER_ACTIVITY_DATA';

export const ADMIN_ACTIVITY_FETCH = 'ADMIN_ACTIVITY_FETCH';
export const ADMIN_ACTIVITY_DATA = 'USER_ACTIVITY_DATA';

export const METRICS_FETCH = 'METRICS_FETCH';
export const METRICS_DATA = 'METRICS_DATA';

export const WITHDRAWS_LIST_DATA = 'withdrawList/WITHDRAWS_LIST_DATA';
export const WITHDRAWS_LIST_FETCH = 'withdrawList/WITHDRAWS_LIST_FETCH';

export const WITHDRAWS_INFO_DATA = 'withdrawInfo/WITHDRAWS_INFO_DATA';
export const WITHDRAWS_INFO_FETCH = 'withdrawInfo/WITHDRAWS_INFO_FETCH';

export const WITHDRAWS_USER_HISTORY_DATA = 'withdrawUserHistory/WITHDRAWS_USER_HISTORY_DATA';
export const WITHDRAWS_USER_HISTORY_FETCH = 'withdrawUserHistory/WITHDRAWS_USER_HISTORY_FETCH';
